const featureCards = [
  { icon: "menu", eyebrow: "01 / Menü", title: "Digitales Menü", description: "Ihre Karte lebt dort, wo Ihre Gäste suchen: schnell, schön und jederzeit aktuell." },
  { icon: "qr", eyebrow: "02 / Zugang", title: "QR-Code", description: "Ein Scan genügt. Platzieren Sie Ihren persönlichen QR-Code auf jedem Tisch." },
  { icon: "star", eyebrow: "03 / Vertrauen", title: "Google Bewertungen", description: "Machen Sie aus zufriedenen Gästen sichtbare Empfehlungen für Ihr Restaurant." },
  { icon: "nfc", eyebrow: "04 / Verbindung", title: "NFC", description: "Ein kurzer Tap verbindet Ihre Gäste direkt mit Menü, Bewertungen und mehr." },
];

const steps = [
  { number: "01", title: "Restaurant erstellen", description: "Profil anlegen und Ihre Marke hinterlegen." },
  { number: "02", title: "Menü einrichten", description: "Gerichte, Preise und Kategorien hinzufügen." },
  { number: "03", title: "QR-Code teilen", description: "Aufstellen, scannen lassen und loslegen." },
];

const plans = [
  { name: "Starter", price: "9", setup: "49", description: "Für kleine Restaurants", features: ["Digitale Speisekarte", "QR-Code", "Menü selbst bearbeiten", "Google Bewertung", "1 Sprache", "Begrenzte Menüfotos", "1 Menü"], cta: "Jetzt starten" },
  { name: "Pro", price: "19", setup: "99", description: "Für wachsende Restaurants", features: ["Alles aus Starter", "Bis zu 5 Sprachen", "NFC-Unterstützung", "Analytics", "Tischbasierte QR-Codes", "Angebote & Kampagnen", "Bis zu 3 Menüs"], featured: true, cta: "Pro wählen" },
  { name: "Business", price: "39", setup: "149", description: "Für mehrere Standorte & Teams", features: ["Alles aus Pro", "10+ Sprachen", "Erweiterte Analytics", "Unbegrenzte Menüs", "Mehrere Standorte", "Mitarbeiterkonten", "Priorisierter Support"], cta: "Business wählen" },
];

function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const common = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.7, strokeLinecap: "round" as const, strokeLinejoin: "round" as const, "aria-hidden": true };
  if (name === "menu") return <svg {...common}><path d="M4 5h16M4 12h16M4 19h10" /></svg>;
  if (name === "qr") return <svg {...common}><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h2M20 14v6M14 18h3" /></svg>;
  if (name === "star") return <svg {...common}><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9L12 3Z" /></svg>;
  if (name === "nfc") return <svg {...common}><path d="M7.5 16.5a6.4 6.4 0 0 1 0-9M11 14a3.6 3.6 0 0 1 0-4M15.5 7.5a6.4 6.4 0 0 1 0 9M13 10a3.6 3.6 0 0 1 0 4M12 12h.01" /></svg>;
  if (name === "arrow") return <svg {...common}><path d="M5 12h13M13 6l6 6-6 6" /></svg>;
  if (name === "check") return <svg {...common}><path d="m5 12 4 4L19 6" /></svg>;
  return <svg {...common}><circle cx="12" cy="12" r="8" /></svg>;
}

function Logo({ light = false }: { light?: boolean }) {
  return <a href="#top" className={`logo ${light ? "logo-light" : ""}`} aria-label="qartivo Startseite"><span className="logo-mark">Q</span><span>qartivo</span></a>;
}

function MenuMockup() {
  return <div className="menu-device" aria-label="Vorschau des digitalen Menüs von La Tavola"><div className="menu-topbar"><span className="tiny-label">LA TAVOLA / MENU</span><span className="menu-avatar">LT</span></div><div className="menu-heading"><p className="menu-kicker">ITALIENISCHE KÜCHE · BASEL</p><h3>La Tavola</h3><p>Benvenuti. Schön, dass Sie da sind.</p></div><div className="menu-tabs"><span className="active">Antipasti</span><span>Pizza</span><span>Pasta</span><span>Dessert</span></div><div className="dish-list"><div className="dish"><div><strong>Burrata Pugliese</strong><p>Tomate · Basilikum · Olivenöl</p></div><b>14.50 €</b></div><div className="dish"><div><strong>Bruschetta Classica</strong><p>San Marzano · Knoblauch · Basilikum</p></div><b>9.50 €</b></div><div className="dish"><div><strong>Vitello Tonnato</strong><p>Kalb · Thunfisch · Kapern</p></div><b>16.90 €</b></div></div><div className="menu-review"><span className="review-star">★</span><div><strong>Gefällt Ihnen unser Essen?</strong><small>Bewerten Sie uns auf Google</small></div><Icon name="arrow" size={16} /></div></div>;
}

function DashboardMockup() {
  return <div className="dashboard" aria-label="Vorschau des Qartivo Dashboards"><aside className="dashboard-sidebar"><div className="dashboard-brand"><span className="mini-q">Q</span> qartivo</div><span className="side-label">WORKSPACE</span><a className="side-active"><Icon name="menu" size={16} /> Übersicht</a><a><Icon name="menu" size={16} /> Menü</a><a><Icon name="star" size={16} /> Bewertungen</a><a><Icon name="qr" size={16} /> QR-Code</a><a><Icon name="nfc" size={16} /> NFC</a><div className="side-bottom"><span>LT</span><small>La Tavola<br /><b>Basel</b></small></div></aside><div className="dashboard-main"><div className="dashboard-header"><div><p className="dash-kicker">MITTWOCH, 18. JUNI 2026</p><h3>Guten Morgen, Luca.</h3></div><span className="notification">◦</span></div><div className="stats-grid"><div><small>MENÜ-AUFRUFE</small><strong>2,846</strong><span className="positive">+18.4%</span></div><div><small>BEWERTUNGEN</small><strong>4.8 <em>★</em></strong><span className="positive">+12.1%</span></div><div><small>AKTIVE QR-CODES</small><strong>08</strong><span className="neutral">Alle aktiv</span></div></div><div className="dashboard-row"><div className="chart-box"><div className="box-title"><b>Menü-Aufrufe</b><span>Letzte 7 Tage⌄</span></div><div className="chart"><span style={{ height: "38%" }} /><span style={{ height: "54%" }} /><span style={{ height: "44%" }} /><span style={{ height: "68%" }} /><span style={{ height: "57%" }} /><span style={{ height: "82%" }} /><span style={{ height: "74%" }} /></div><div className="chart-days"><span>Mo</span><span>Di</span><span>Mi</span><span>Do</span><span>Fr</span><span>Sa</span><span>So</span></div></div><div className="activity-box"><div className="box-title"><b>Zuletzt aktiv</b><span>Alle</span></div><p><i className="activity-dot green" /> Menü aktualisiert <small>vor 12 Min.</small></p><p><i className="activity-dot" /> Neue Bewertung <small>vor 38 Min.</small></p><p><i className="activity-dot" /> QR-Code gescannt <small>vor 1 Std.</small></p></div></div></div></div>;
}

export default function Home() {
  return <main id="top">
    <nav className="site-nav"><div className="nav-inner"><Logo /><div className="nav-links"><a href="#funktionen">Funktionen</a><a href="#so-funktionierts">So funktioniert&apos;s</a><a href="#preise">Preise</a><a href="#demo">Demo</a></div><div className="nav-actions"><a href="/login" className="login-link">Login</a><a href="/register" className="button button-small">Kostenlos starten <Icon name="arrow" size={15} /></a></div><details className="mobile-menu"><summary aria-label="Menü öffnen"><span /><span /></summary><div className="mobile-menu-panel"><a href="#funktionen">Funktionen</a><a href="#so-funktionierts">So funktioniert&apos;s</a><a href="#preise">Preise</a><a href="#demo">Demo</a><a href="/login">Login</a><a href="/register" className="button">Kostenlos starten</a></div></details></div></nav>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-dot" /> Die digitale Basis für Ihr Restaurant</div><h1>Ihr Restaurant.<br /><span>Digitaler.</span><br />Einfacher.</h1><p>Mit Qartivo verwandeln Sie Ihr Restaurant in ein modernes digitales Erlebnis – mit QR-Menü, Google Bewertungen, NFC und zentraler Verwaltung.</p><div className="hero-actions"><a href="/register" className="button">Kostenlos starten <Icon name="arrow" size={17} /></a><a href="#demo" className="text-button">Demo ansehen <Icon name="arrow" size={17} /></a></div><div className="hero-proof"><span><Icon name="check" size={14} /> Keine Kreditkarte</span><span><Icon name="check" size={14} /> In 5 Min. eingerichtet</span></div></div><div id="demo" className="hero-product"><div className="product-glow" /><div className="product-window"><div className="window-bar"><span /><span /><span /><small>qartivo / la-tavola</small></div><MenuMockup /></div><div className="floating-badge"><span className="badge-icon"><Icon name="star" size={16} /></span><div><strong>4.8 / 5.0</strong><small>Google Bewertung</small></div></div></div></div></section>
    <section className="trust-strip"><div className="content-width trust-inner"><span className="trust-intro">Alles, was digital zählt.</span><div className="trust-items"><span><Icon name="menu" size={17} /> Digitales Menü</span><span><Icon name="qr" size={17} /> QR-Code</span><span><Icon name="star" size={17} /> Google Bewertungen</span><span><Icon name="nfc" size={17} /> NFC</span><span><Icon name="check" size={17} /> Zentrale Verwaltung</span></div></div></section>
    <section id="funktionen" className="section features-section"><div className="content-width"><div className="section-heading"><div><p className="section-label">Die Qartivo Plattform</p><h2>Alles, was Ihr Restaurant<br /><span>digital braucht.</span></h2></div><p>Weniger Tools. Weniger Aufwand.<br />Mehr Zeit für Ihre Gäste.</p></div><div className="feature-grid">{featureCards.map((feature) => <article className="feature-card" key={feature.title}><div className="feature-icon"><Icon name={feature.icon} size={22} /></div><p className="card-eyebrow">{feature.eyebrow}</p><h3>{feature.title}</h3><p>{feature.description}</p><a href="#demo" aria-label={`${feature.title} entdecken`}><Icon name="arrow" size={17} /></a></article>)}</div></div></section>
    <section className="showcase-section"><div className="content-width showcase-grid"><div className="showcase-copy"><p className="section-label">Ein Ort für alles</p><h2>Ein System.<br /><span>Alles unter Kontrolle.</span></h2><p>Von der ersten Einrichtung bis zur täglichen Auswertung: Qartivo gibt Ihnen die Übersicht, die Sie brauchen, und lässt den Rest einfach aussehen.</p><div className="showcase-list"><div><span>01</span><p><strong>Einfach verwalten</strong><br />Änderungen sind sofort live.</p></div><div><span>02</span><p><strong>Klar entscheiden</strong><br />Wichtige Zahlen auf einen Blick.</p></div></div><a href="#preise" className="text-button dark-button">Qartivo entdecken <Icon name="arrow" size={17} /></a></div><div className="dashboard-wrap"><DashboardMockup /></div></div></section>
    <section id="so-funktionierts" className="section steps-section"><div className="content-width"><div className="center-heading"><p className="section-label">Der einfache Start</p><h2>In drei Schritten <span>digital.</span></h2><p>Von der Idee zum ersten Scan. Ohne Schulung, ohne Agentur, ohne Umwege.</p></div><div className="steps-grid">{steps.map((step, index) => <div className="step" key={step.number}><div className="step-top"><span>{step.number}</span>{index < steps.length - 1 && <i />}</div><h3>{step.title}</h3><p>{step.description}</p></div>)}</div></div></section>
    <section className="reviews-section"><div className="content-width reviews-grid"><div className="review-quote"><p className="section-label">Ihre Gäste sprechen für Sie</p><h2>Mehr Bewertungen.<br /><span>Mehr Vertrauen.</span></h2><p>Der Moment nach dem Essen ist der beste Moment für eine Bewertung. Qartivo macht ihn einfach.</p><a href="#preise" className="text-button">Mehr erfahren <Icon name="arrow" size={17} /></a></div><div className="google-card"><div className="google-head"><span className="google-g">G</span><div><strong>Google</strong><small>Bewertungen</small></div><span className="google-dots">•••</span></div><div className="rating-row"><strong>4.8</strong><div><div className="stars">★★★★★</div><small>127 Bewertungen</small></div></div><div className="rating-bars"><span><b>5</b><i><em style={{ width: "88%" }} /></i></span><span><b>4</b><i><em style={{ width: "68%" }} /></i></span><span><b>3</b><i><em style={{ width: "16%" }} /></i></span><span><b>2</b><i><em style={{ width: "8%" }} /></i></span><span><b>1</b><i><em style={{ width: "5%" }} /></i></span></div><div className="recent-review"><div className="review-person"><span>MS</span><strong>Maria S.</strong><small>vor 2 Tagen</small><b>★★★★★</b></div><p>„Wunderbares Essen und ein sehr schöner Abend. Wir kommen gerne wieder!“</p></div></div></div></section>
    <section id="preise" className="section pricing-section"><div className="content-width"><div className="center-heading"><p className="section-label">Transparent und fair</p><h2>Der passende Plan<br /><span>für Ihren Betrieb.</span></h2><p>Wählen Sie die passende Basis für Ihr Restaurant.</p></div><div className="pricing-grid">{plans.map((plan) => <article className={`pricing-card ${plan.featured ? "featured" : ""}`} key={plan.name}>{plan.featured && <div className="popular">Beliebt</div>}<p className="plan-name">{plan.name}</p><p className="plan-description">{plan.description}</p><div className="price"><strong>{plan.price} €</strong><span>/ Monat</span></div><div className="setup-fee"><span>Einmalige Einrichtung</span><strong>{plan.setup} €</strong></div><a href="/register" className={`button ${plan.featured ? "button-light" : ""}`}>{plan.cta} <Icon name="arrow" size={16} /></a><div className="plan-divider" /><ul>{plan.features.map((feature) => <li key={feature}><Icon name="check" size={16} /> {feature}</li>)}</ul><p className="pricing-note">Einmalige Einrichtung + monatliche Nutzung</p></article>)}</div></div></section>
    <section id="login" className="final-cta"><div className="content-width cta-inner"><div><p className="section-label">Der nächste Schritt</p><h2>Bereit für ein<br /><span>moderneres Restaurant?</span></h2></div><div><p>Starten Sie heute kostenlos mit Qartivo. Ihre Gäste werden den Unterschied merken.</p><a href="/register" className="button button-light">Kostenlos starten <Icon name="arrow" size={17} /></a></div></div></section>
    <footer><div className="content-width footer-top"><div><Logo light /><p>Die digitale Basis für moderne Restaurants.</p></div><div className="footer-links"><div><strong>Produkt</strong><a href="#funktionen">Funktionen</a><a href="#preise">Preise</a><a href="#demo">Demo</a></div><div><strong>Unternehmen</strong><a href="#so-funktionierts">Über Qartivo</a><a href="/login">Kontakt</a><a href="/login">Login</a></div><div><strong>Rechtliches</strong><a href="#login">Impressum</a><a href="#login">Datenschutz</a></div></div></div><div className="content-width footer-bottom"><span>© 2026 qartivo. Alle Rechte vorbehalten.</span><span>Made for hospitality.</span></div></footer>
  </main>;
}
